<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>$schema</key>
	<string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
	<key>fileTypes</key>
	<array>
		<string>m</string>
	</array>
	<key>name</key>
	<string>M Language</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#expression</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>bracketed-block-comment</key>
		<dict>
			<key>begin</key>
			<string>#\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.block.mlang</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.block.mlang</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.comment.block.bracketed.mlang</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#doc-expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment-char</string>
				</dict>
			</array>
		</dict>
		<key>bracketed-expression</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.mlang</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.mlang</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.bracketed.mlang</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#atomic-expression</string>
				</dict>
			</array>
		</dict>
		<key>char-expression</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.mlang</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[^']|''</string>
					<key>name</key>
					<string>string.quoted.single.mlang</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#doc-comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#parenthesized-block-comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bracketed-block-comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#line-comment</string>
				</dict>
			</array>
		</dict>
		<key>comment-char</key>
		<dict>
			<key>match</key>
			<string>.</string>
			<key>name</key>
			<string>comment.mlang</string>
		</dict>
		<key>doc-expression</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parenthesized-expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bracketed-expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number-expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#symbol-literal-expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>expression</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#parenthesized-expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bracketed-expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number-expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#symbol-expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#char-expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>line-comment</key>
		<dict>
			<key>begin</key>
			<string>#</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.line.mlang</string>
				</dict>
			</dict>
			<key>end</key>
			<string>
|
</string>
			<key>name</key>
			<string>meta.comment.line.mlang</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment-char</string>
				</dict>
			</array>
		</dict>
		<key>number-expression</key>
		<dict>
			<key>match</key>
			<string>[-+]?([0-9]*\.[0-9]+|[0-9]+)</string>
			<key>name</key>
			<string>constant.numeric.mlang</string>
		</dict>
		<key>parenthesized-block-comment</key>
		<dict>
			<key>begin</key>
			<string>#\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.block.mlang</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.block.mlang</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.comment.block.parenthesized.mlang</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#doc-expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment-char</string>
				</dict>
			</array>
		</dict>
		<key>parenthesized-expression</key>
		<dict>
			<key>begin</key>
			<string>\(([a-zA-Z0-9]([a-zA-Z0-9]|[!$%&amp;*+/|:&lt;=&gt;?@^~'=-])*)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.mlang</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.mlang</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.mlang</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.parenthesized.mlang</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
		<key>string-expression</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.mlang</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[^"]|""</string>
					<key>name</key>
					<string>string.quoted.mlang</string>
				</dict>
			</array>
		</dict>
		<key>symbol-expression</key>
		<dict>
			<key>match</key>
			<string>[a-zA-Z0-9]([a-zA-Z0-9]|[!$%&amp;*+/|:&lt;=&gt;?@^~'=-])*</string>
			<key>name</key>
			<string>variable.mlang</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.m</string>
</dict>
</plist>
